const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Blue Jeans',
      slug: 'blue-jeans',
      category: 'Jeans',
      image: '/images/pants1.jpg',
      price: 80,
      brand: "Levi's",
      rating: 4.8,
      numReviews: 22,
      countInStock: 15,
      description: 'High-quality blue jeans made from durable denim fabric.',
    },
    {
      name: 'Running Shoes',
      slug: 'running-shoes',
      category: 'Shoes',
      image: '/images/pants2.jpg',
      price: 120,
      brand: 'Asics',
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
      description:
        'Lightweight and breathable running shoes with excellent traction.',
    },
    {
      name: 'Red Sweater',
      slug: 'red-sweater',
      category: 'Sweaters',
      image: '/images/shirt2.jpg',
      price: 60,
      brand: 'Gap',
      rating: 3.9,
      numReviews: 8,
      countInStock: 18,
      description: 'A soft and cozy red sweater with a classic design.',
    },
    {
      name: 'Leather Jacket',
      slug: 'leather-jacket',
      category: 'Jackets',
      image: '/images/shirt2.jpg',
      price: 200,
      brand: 'Schott NYC',
      rating: 4.5,
      numReviews: 15,
      countInStock: 3,
      description:
        'A timeless leather jacket with a slim fit and zippered pockets.',
    },
    {
      name: 'White T-Shirt',
      slug: 'white-tshirt',
      category: 'T-Shirts',
      image: '/images/shirt2.jpg',
      price: 25,
      brand: 'H&M',
      rating: 4.0,
      numReviews: 6,
      countInStock: 30,
      description:
        'A simple and versatile white t-shirt made from soft cotton fabric.',
    },
  ],
};

export default data;
